server:
   forward-headers-strategy: native

spring:
   application:
      name: sse-gateway-service
   cloud:
      gateway:
         discovery:
            locator:
               enabled: true
         default-filters:
           - TokenRelay=
           #- StripPrefix=1

management:
   endpoints:
      web:
         exposure:
            include:
            - mappings
            - env
            - health
            - info
            - '*'
eureka:
   client:
      registerWithEureka: false
      serviceUrl:
         defaultZone: ${eureka-zone}
      healthcheck:
         enabled: true
