
spring:
   application:
      name: sse-gateway-service
   cloud:
      gateway:
         discovery:
            locator:
               enabled: true
         default-filters:
           - TokenRelay=
           - StripPrefix=1
         routes:
           - id: registry
             uri: lb://registry
             predicates:
               - Path=/registry/**

management:
   endpoints:
      web:
         exposure:
            include:
            - mappings
            - env
            - health
            - info
            - '*'
eureka:
   client:
      registerWithEureka: false
      serviceUrl:
         defaultZone: ${eureka-ip}/eureka
      healthcheck:
         enabled: true
